version: "3.8"

services:
  backend:
    build: ./
    ports:
      - 3000:3000
    environment:
      DB_URL: mongodb://database:27017/vindly
    # volumes:
    #   - ./backend:/app
    # command: ./docker-entrypoint.sh
  database:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db 
volumes:
  vidly: 